### ISSUE TITLE
Cars despawning 

### ISSUE THREAD

**Issue by jamesc24** [TheStonedTurtle/mellotrainer#26]
Unfortunately I’m unable to use this on my RP server because people’s vehicles keep on despawning. Since removing this trainer we haven’t had the problem since. 

I’d love to see this fixed because I would use this trainer above the lambda menu, as you can actually restrict the features.

**Comment by blockba5her** [comment]
There is some code somewhere in the spawning of the cars where it turns them off as a mission entity (mission entities basically never despawn), you could edit that part of the code to find what is happening...
