### ISSUE TITLE
Weapon Loadouts

### ISSUE THREAD

**Issue by matty45** [TheStonedTurtle/mellotrainer#6]
This is not an issue but rather a suggestion. It would be cool to be able to save the weapons you have, just like you would save skins or vehicles. It would be useful so you would not have to manually get all your weapons and attachments back each time you die.

**Comment by TheStonedTurtle** [comment]
As @WolfKnight98 mentioned on the forums there are many ways we could do this and we aren't sure which way everyone would prefer.

1) Save Individual Weapons
2) Save entire Weapon Wheel
3) Both?

Unless WolfKnight tackles this sooner it will also be done when MySQL support is added.
